<?php
/**
 * @file
 * Code for the Banner Support feature.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function banner_support_ctools_plugin_api($module = NULL, $api = NULL) {
  return common_support_ctools_plugin_api($module, $api);
}

/**
 * Implements hook_views_api().
 */
function banner_support_views_api($module = NULL, $api = NULL) {
  return common_support_views_api($module, $api);
}

/**
 * Implements hook_common_support_import().
 */
function banner_support_common_support_import() {
  return array(
    'node_type',
    'field_base',
    'field_instance',
    'variable',
  );
}

/**
 * Implements hook_common_support_delete_import().
 */
function banner_support_common_support_delete_import() {
  return array(
    'node_type',
    'field_instance',
    'variable',
  );
}

/**
 * Implements hook_node_view_alter().
 */
function banner_support_node_view_alter(&$build) {
  // Switch banner view modes on banner logic.
  // This works b/c banners are only shown in a views block.
  // If body has content, use teaser.
  if ($build['#entity_type'] == 'banner') {
    if (!empty($build['field_banner_body'])) {
      $build['#view_mode'] = 'teaser';
    }
    else {
      $build['#view_mode'] = 'teaser2';
    }
  }
}
