name = sidebar
description = A single sidebar interior page
preview = sidebar-layout-preview.png
template = sidebar-layout

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.css
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.no-query.css

; ========================================
; Regions
; ========================================
regions[messages] = Messages
regions[user_bar] = User Bar
regions[mobile_nav] = Mobile Navigation
regions[pre_header] = Pre-Header
regions[header] = Header
regions[branding] = Branding
regions[navigation] = Navigation
regions[cart] = Cart
regions[pre_content] = Pre-Content
regions[content] = Content
regions[content_1] = Content 1
regions[content_2] = Content 2
regions[post_content] = Post-Content
regions[sidebar] = Sidebar
regions[pre_footer] = Pre-Footer
regions[footer] = Footer
regions[footer_1] = Footer Section 1
regions[footer_2] = Footer Section 2