<?php
/**
 * @file
 * Code for the Articles Support feature.
 */

include_once('articles_support.features.inc');

/**
 * Returns an image to use in the article teaser.
 *
 * @param $node
 *   The article node to get and image for.
 * @return $image
 *   An image file render array or null if none can be found.
 * 
 */
function articles_support_get_article_teaser_image($node, $view_mode = 'full') {
  //if there is an article video, use that.
  $image = array();
  if (!empty($node->field_article_video)) {
    $settings = array(
      'label' => 'hidden',
      'module' => 'video_embed_field',
      'settings' => array(
       'description' => 1,
       'description_position' => 'bottom',
       'image_style' => 'articles_teaser_square_switcher',
      ),
      'type' => 'video_embed_field_thumbnail',
      'weight' => 9,
    );
    $image = field_view_value('node', $node, 'field_article_video', $node->field_article_video[LANGUAGE_NONE][0], $settings);
  }
  elseif (!empty($node->field_article_images)) { //else if there's a image, use that
    $settings = array(
      'label' => 'above',
      'module' => 'image',
      'settings' => array(
        'image_style' => 'articles_teaser_square_switcher',
      ),
      'type' => 'image',
      'weight' => 10,
     );
    $image = field_view_value('node', $node, 'field_article_images', $node->field_article_images[LANGUAGE_NONE][0], $settings);
  }
  return $image;
}


function articles_support_node_view($node, $view_mode, $langcode) {
  // Proceed if this is a news article.
  if ($node->type == 'news_article') {
    // Proceed by view mode.
    switch($view_mode) {
      case "full":
        // Gallery.
        $gallery = views_get_view('articles');
        $gallery->set_display('gallery');
        $data = $gallery->preview('gallery', array($node->nid));
        //count images + videos
        if ($gallery->result) {
          $items = count($gallery->result[0]->field_field_article_images) + count($gallery->result[0]->field_field_article_video);
          if ($items > 1) {
            $node->content['gallery'] = array(
              '#theme' => 'block_wrapper',
              '#data' => theme('show_hide', array('element' => $data, 'height' => 175)),
              '#title' => $gallery->get_title(),
            );
          }
        }

        // Entity Pager.
        //node pager block
        if (module_exists('entity_pager')) {
          $node->content['article_pager'] = array(
            '#theme' => 'embed_block',
            '#module' => 'entity_pager',
            '#delta' => 'entity_pager_1',
          );
        }

        // Recent articles (view).
        $node->content['recent_articles'] = array(
          '#theme' => 'view_embed',
          '#view' => 'articles',
          '#display' => 'recent',
          '#args' => array($node->nid),
        );
        common_support_view_check($node->content['recent_articles']);
        break;
      case "teaser":
        // Video/image switcharoo.
        $node->content['teaser_image'] = articles_support_get_article_teaser_image($node);
        // Link to title as a clickable select link.
        $node->content['title_link'] = array(
          '#theme' => 'link',
          '#path' => 'node/' . $node->nid,
          '#text' => filter_xss($node->title),
          '#options' => array(
            'html' => FALSE,
            'attributes' => array(
              'class' => array(
                'clickable-select',
              ),
            ),
          ),
        );
        // Re Write the submitted date.
        $stamp = $node->created;
        $node->content['submitted'] = array(
          '#markup' => date('F n, Y', $stamp),
        );
        break;
      case "teaser2":
        // Video/image switcharoo.
        $node->content['teaser_image'] = articles_support_get_article_teaser_image($node);
        // Link to title as a clickable select link.
        $node->content['title_link'] = array(
          '#theme' => 'link',
          '#path' => 'node/' . $node->nid,
          '#text' => filter_xss($node->title),
          '#options' => array(
            'html' => FALSE,
            'attributes' => array(
              'class' => array(
                'clickable-select',
              ),
            ),
          ),
        );
        // Re Write the submitted date.
        $stamp = $node->created;
        $node->content['submitted'] = array(
          '#markup' => date('F n, Y', $stamp),
        );
        break;
    }
  }
}


function articles_support_field_extra_fields() {
  $extra = array();
  $extra['node']['news_article']['display']['gallery'] = array(
    'label' => t('News Article Gallery'),
    'description' => t('Gallery of images and/or videos in the news article. (Full/Default View Mode Only)'),
    'weight' => 0,
  );
  if (module_exists('entity_pager')) {
    $extra['node']['news_article']['display']['article_pager'] = array(
      'label' => t('News Article Entity Pager'),
      'description' => t('Pager for thumbing through articles. (Full/Default View Mode Only)'),
      'weight' => 0,
    );
  }
  $extra['node']['news_article']['display']['recent_articles'] = array(
    'label' => t('Recent News Articles'),
    'description' => t('View display of recent articles (view=articles, display=recent), (Full/Default View Mode Only)'),
    'weight' => 0,
  );
  $extra['node']['news_article']['display']['teaser_image'] = array(
    'label' => t('Article Teaser Image'),
    'description' => t('Teaser image provided as either video thumbnail or image thumbnail. (Teaser/Another Teaser Mode View Mode Only)'),
    'weight' => 0,
  );
  $extra['node']['news_article']['display']['title_link'] = array(
    'label' => t('Article Title as Clickable Select Link'),
    'description' => t('Node title as a clickable-select link. (Teaser/Another Teaser Mode View Mode Only)'),
    'weight' => 0,
  );
  return $extra;
}
