<?php
/**
 * @file
 * Code for the Articles Support feature.
 */

/**
 * Returns an image to use in the article teaser.
 *
 * @param $node
 *   The article node to get and image for.
 * @return $image
 *   An image file render array or null if none can be found.
 * 
 */
function articles_support_get_article_teaser_image($node, $view_mode = 'full') {
  //if there is an article video, use that.
  $image = array();
  if (!empty($node->field_article_video)) {
    $settings = array(
      'label' => 'hidden',
      'module' => 'video_embed_field',
      'settings' => array(
       'description' => 1,
       'description_position' => 'bottom',
       'image_style' => 'articles_teaser_square_switcher',
      ),
      'type' => 'video_embed_field_thumbnail',
      'weight' => 9,
    );
    $image = field_view_value('node', $node, 'field_article_video', $node->field_article_video[LANGUAGE_NONE][0], $settings);
  }
  elseif (!empty($node->field_article_images)) { //else if there's a image, use that
    $settings = array(
      'label' => 'above',
      'module' => 'image',
      'settings' => array(
        'image_style' => 'articles_teaser_square_switcher',
      ),
      'type' => 'image',
      'weight' => 10,
     );
    $image = field_view_value('node', $node, 'field_article_images', $node->field_article_images[LANGUAGE_NONE][0], $settings);
  }
  return $image;
}

function articles_support_preprocess_node(&$vars) {
  // Proceed if this is a news article.
  if ($vars['node']->type == 'news_article') {
    // Proceed by view mode.
    switch($vars['view_mode']) {
      case "full":
        // Gallery.
        $gallery = views_get_view('articles');
        $gallery->set_display('gallery');
        $data = $gallery->preview('gallery', array($vars['node']->nid));
        //count images + videos
        if ($gallery->result) {
          $items = count($gallery->result[0]->field_field_article_images) + count($gallery->result[0]->field_field_article_video);
          if ($items > 1) {
            $field_content = array(
              '#theme' => 'block_wrapper',
              '#data' => theme('show_hide', array('element' => $data, 'height' => 175)),
              '#title' => $gallery->get_title(),
            );
            $vars['news_article_gallery'] = drupal_render($field_content);
          }
        }
        break;
      default:
        // Video/image switcharoo.
        $field_content = articles_support_get_article_teaser_image($vars['node']);
        $vars['teaser_image'] = $field_content;
        // Link to title as a clickable select link.
        /*$node['title_link'] = array(
          '#theme' => 'link',
          '#path' => 'node/' . $vars['#node']->nid,
          '#text' => filter_xss($vars['#node']->title),
          '#options' => array(
            'html' => FALSE,
            'attributes' => array(
              'class' => array(
                'clickable-select',
              ),
            ),
          ),
        );*/
        // Re Write the submitted date.
        $stamp = $vars['node']->created;
        $field_content = array(
          '#markup' => date('F n, Y', $stamp),
        );
        $vars['submitted'] = $field_content;
    }
  }
}

/**
 * Implements hook_ds_layout_info().
 */
function articles_support_ds_layout_info() {
  $path = drupal_get_path('module', 'articles_support');

  $layouts = array(
    'articles_support_1' => array(
      'label' => t('Article Layout Gen 1'),
      'path' => $path . '/layouts/articles_support_1',
      'regions' => array(
        'article_content' => t('Content'),
      ),
      'css' => TRUE,
      // optional, form only applies to node form at this point.
      'form' => TRUE,
    ),
  );

  return $layouts;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function articles_support_ctools_plugin_api($module = NULL, $api = NULL) {
  return common_support_ctools_plugin_api($module, $api);
}

/**
 * Implements hook_views_api().
 */
function articles_support_views_api($module = NULL, $api = NULL) {
  return common_support_views_api($module, $api);
}
