name = uc.1col+sidebar.10CRows
description = Un-constrained layout having 1 column with a sidebar, and the column has 10 content-rows
preview = uc.1col+sidebar.10CRows.png
template = uc.1col+sidebar.10CRows.tpl.php

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/uc.1col+sidebar.10CRows/uc.1col+sidebar.10CRows.css
stylesheets[all][] = css/layouts/uc.1col+sidebar.10CRows/uc.1col+sidebar.10CRows.css

; ========================================
; Scripts
; ========================================


; ========================================
; Regions
; ========================================
regions[mobile_nav] = Mobile Navigation
regions[header] = Header
regions[branding] = Branding
regions[navigation] = Navigation
regions[pre_content] = Pre-Content
regions[content_1] = Content 1
regions[content_2] = Content 2
regions[content_3] = Content 3
regions[content_4] = Content 4
regions[content_5] = Content 5
regions[content_6] = Content 6
regions[content_7] = Content 7
regions[content_7] = Content 8
regions[content_7] = Content 9
regions[content_7] = Content 10
regions[pre_footer] = Pre-Footer
regions[footer] = Footer
regions[footer_1] = Footer Section 1
regions[footer_2] = Footer Section 2
