name = no-sidebar
description = Layout for pages with no sidebar content
preview = no-sidebar-layout-preview.png
template = no-sidebar-layout

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/no-sidebar/no-sidebar.layout.css
stylesheets[all][] = css/layouts/no-sidebar/no-sidebar.layout.no-query.css

; ========================================
; Regions
; ========================================
regions[messages] = Messages
regions[user_bar] = User Bar
regions[mobile_nav] = Mobile Navigation
regions[pre_header] = Pre-Header
regions[header] = Header
regions[branding] = Branding
regions[navigation] = Navigation
regions[cart] = Cart
regions[pre_content] = Pre-Content
regions[content] = Content
regions[post_content] = Post-Content
regions[pre_footer] = Pre-Footer
regions[footer] = Footer
regions[footer_1] = Footer Section 1
regions[footer_2] = Footer Section 2