<?php
/**
 * @file
 * waypoints_ui.module
 */

/**
 * Implements hook_init().
 */
function waypoints_ui_init() {
  $settings['waypointsUI'] = array();
  $waypoints = variable_get('waypoints_ui_waypoints', array());
  // Convert waypoint settings into Drupal js setting.
  foreach($waypoints as $key => $waypoint) {
    $settings['waypointsUI'][$waypoint['attach_element']]['attach_element'] = $waypoint['attach_element'];
    $settings['waypointsUI'][$waypoint['attach_element']]['toggle_class'] = $waypoint['toggle_class'];
    $settings['waypointsUI'][$waypoint['attach_element']]['toggle_offset'] = $waypoint['toggle_offset'];
    $settings['waypointsUI'][$waypoint['attach_element']]['same_element'] = $waypoint['same_element'];
    $settings['waypointsUI'][$waypoint['attach_element']]['toggle_element'] = $waypoint['toggle_element'];
  }
  drupal_add_js($settings, 'setting');
}

/**
 * Implements hook_permission().
 */
function waypoints_ui_permission() {
  $permissions = array();
  $permissions['configure waypoints_ui'] = array(
    'title' => t('Configure Waypoints UI'),
    'description' => t('Allows a user to add waypoint bindings using the ui'),
    'restrict access' => TRUE,
    'warning' => t('Giving this permission to some users could result in some funky-ass website behaviors.')
  );
  return $permissions;
}

/**
 * Implements hook_menu().
 */
function waypoints_ui_menu() {
  $items = array();
  $items['admin/config/user-interface/waypoints/ui'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => t('Waypoints UI'),
    'access arguments' => array('configure waypoints_ui'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('waypoints_ui_settings_form'),
    'file' => 'includes/waypoints_ui.admin.inc',
    'weight' => 10,
  );
  $items['admin/config/user-interface/waypoints/settings'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => t('Waypoints Module Settings'),
    'weight' => -10,
  );

  return $items;
}
