<?php
/**
 * @file
 * Code for the common support.
 */

/**
 * Implements hook_common_support_import().
 */
function common_support_common_support_import() {
  return array(
    'filters',
    'variable',
    'wysiwyg'
  );
}

/**
 * Implements hook_modules_installed().
 * Imports any assets that a module specifies should
 * be imported when the module is installed.
 */
function common_support_modules_enabled($modules) {
  module_load_include('inc', 'common_support', 'common_support.importers');
  $implementations = module_implements('common_support_import');
  foreach($modules as $module) {
    if (in_array($module, $implementations)) {
      $assets = module_invoke($module, 'common_support_import');
      if (is_array($assets)) {
        // Entities must be imported first.
        $importables = array(
          'node',
          'commerce_product',
        );
        foreach($assets as $key => $asset) {
          if (in_array($asset, $importables)) {
            unset ($assets[$key]);
            array_unshift($assets, $asset);
          }
        }
        common_support_import($module, $assets);
      }
    }
  }
}

/**
 * Implements hook_block_view().
 * If using ds_extras page title processing
 * and blockify together, need to update the
 * page title via ds first.
 */
function common_support_block_view_alter(&$data, $block) {
  // This block only exists if blockify is enabled.
  if ($block->delta == 'blockify-page-title') {
    // Alter the block title ala ds_extras.
    if (module_exists('ds_extras')) {
      $page_title = drupal_static('ds_page_title');
      if (!empty($page_title['head_title'])) {
        drupal_set_title($page_title['head_title']);
      }
    }
    $data = array(
      'subject' => '',
      'content' => blockify_get_content('blockify-page-title'),
    );
  }
}

/**
 * Implements hook_modules_uninstalled.
 * Deletes any assets that a module specifies should
 * be disabled when the module is un-installed.
 */
function common_support_modules_uninstalled($modules) {
  module_load_include('inc', 'common_support', 'common_support.importers');
  $implementations = module_implements('common_support_delete_import');
  foreach($modules as $module) {
    if (in_array($module, $implementations)) {
      $assets = module_invoke($module, 'common_support_delete_import');
      if (is_array($assets)) {
        common_support_delete_imports($assets);
      }
    }
  }
}

/**
 * Implements hook_menu().
 */
function common_support_menu() {
  $items = array();
  $items['page-not-found'] = array(
    'type' => MENU_CALLBACK,
    'title' => t('Page Not Found'),
    'page callback' => 'common_support_404_page',
    'access arguments' => array('access content'),
    'file' => 'common_support.pages.inc',
  );
  $items['home'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'common_support_blank_page',
    'access arguments' => array('access content'),
    'file' => 'common_support.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 * Have to force /search/node to use a correct
 * title otherwise it defaults to the homepage title.
 */
function common_support_menu_alter(&$items) {
  $items['search/node']['title'] = t('Search');
  $items['search/node']['type'] = MENU_NORMAL_ITEM;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function common_support_form_system_site_information_settings_alter(&$form, $form_state) {
  // Add custom 404 page settings
  $form['error_page']['404_page'] = array(
    '#type' => 'fieldset',
    '#title' => t('404 Page Content'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['error_page']['404_page']['common_support_404_headline'] = array(
    '#type' => 'text_format',
    '#title' => t('404 Page Headline'),
    '#description' => t('This will be displayed above the 404 page body.'),
    '#default_format' => 'filtered_html',
    '#default_value' => common_support_default_404_page_headline(),
  );
  $form['error_page']['404_page']['common_support_404_body'] = array(
    '#type' => 'text_format',
    '#title' => t('404 Page Body'),
    '#description' => t('This will be displayed below the 404 page headline.'),
    '#default_format' => 'filtered_html',
    '#default_value' => common_support_default_404_page_body(),
  );
}

/**
 * Returns default copy for the 404 page.
 */
function common_support_default_404_page_headline() {
  $content = "<p>Sorry, that page can't be found on the site.</p>";
  return $content;
}

/**
 * Returns default copy for the 404 page.
 */
function common_support_default_404_page_body() {
  $content = "<p>Sorry, we couldn't find the page you were looking for. Why not try and use the " . l(t('Search'), 'search'). " or " . l(t('Return to the Home Page'), '<front>') . ".</p>";
  return $content;
}

/**
 * Implements hook_node_view().
 */
function common_support_node_view($node, $view_mode, $langcode) {
  // Can have share links on any node type.
  $node->content['share_links'] = array(
    '#theme' => 'share_links',
    '#link_href' => url(drupal_get_path_alias('node/' . $node->nid),
      array('absolute' => TRUE)),
    '#nid' => $node->nid,
  );
}

/**
 * Implements hook_extra_fields().
 */
function common_support_field_extra_fields() {
  // Get all node types with see tickets reference field.
  $node_types = node_type_get_types();
  $extra = array();
  foreach ($node_types as $type => $type_object) {
    $extra['node'][$type]['display']['share_links'] = array(
      'label' => t('Addthis Social Share Links'),
      'description' => t('Addthis social share links.'),
      'weight' => 0,
    );
  }
  return $extra;
}

/**
 * Implements hook_theme().
 */
function common_support_theme() {
  $themes = array();
  $themes['share_links'] = array(
    'variables' => array('fb_scrape'=>false, 'nid'=>null, 'link_href' => null),
    'file' => 'theme/common_support.theme.inc',
  );
  $themes['common_support_addthis'] = array(
    'variables' => array('url' => null),
    'file' => 'theme/common_support.theme.inc',
  );
  $themes['show_hide_more_link'] = array(
    'variables' => array('more_text' => 'Show More', 'less_text' => 'Show Less', 'height' => null),
    'file' => 'theme/common_support.theme.inc',
  );
  $themes['show_hide'] = array(
    'variables' => array('element' => null, 'height' => null, 'more_text' => 'Show More', 'less_text' => 'Show Less'),
    'file' => 'theme/common_support.theme.inc',
  );
  $themes['block_wrapper'] = array(
    'variables' => array('data' => '', 'title' => ''),
    'file' => 'theme/common_support.theme.inc',
  );
  $themes['view_embed'] = array(
    'variables' => array('view' => '', 'display' => '', 'args' => array()),
    'file' => 'theme/common_support.theme.inc',
  );
  $themes['embed_block'] = array(
    'variables' => array('module' => null, 'delta' => null),
    'file' => 'theme/common_support.theme.inc',
  );
  $themes['common_support_404_page'] = array(
    'variables' => array(),
    'path' => drupal_get_path('module', 'common_support') . '/theme',
    'file' => 'common_support.theme.inc',
    'template' => 'common-support-404-page',
  );
  return $themes;
}

/**
 * Helper function orders a page scrape from facebook.
 * @param $url
 */
function common_support_order_fb_scrape($url) {
  // Order an fb scrape if desired.
  $ch = curl_init("https://graph.facebook.com/?id={$url}&scrape=true");
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  curl_exec($ch);
  curl_close($ch);
}


/**
 * Implements hook_preprocess_node().
 */
function common_support_preprocess_node(&$vars) {
  // Add theme hook suggestions for nodes based on view mode.
  $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__' . $vars['view_mode'];
}

/**
 * Implements hook_preprocess_html().
 */
function common_support_preprocess_html(&$vars) {
  $add_this_id = variable_get('social_share_addthis_publisher_id', 'ra-5519fea46a8a52a2');
  if (isset($add_this_id)) {
    // Inject the addthis js.
    $addthis_js_url = "https://s7.addthis.com/js/300/addthis_widget.js#pubid=$add_this_id";
    drupal_add_js($addthis_js_url, array('type' => 'external', 'scope' => 'header', 'group' => JS_LIBRARY, 'every_page' => TRUE, 'weight' => -10000));
  }
  // Set metatags variable if exists.
  if (module_exists('metatag') && drupal_is_front_page()) {
    $tags = array();
    $instance = 'global:frontpage';
    $build = metatag_metatags_view($instance, $tags);
    render($build);
  }
}


/**
 * Implements hook_field_formatter_info().
 */
function common_support_field_formatter_info() {
  return array(
    'common_support_schema_list' => array(
      'label' => t("Schema List"),
      'field types' => array('text', 'text_long'),
      'settings' => array(
        'common_support_list_type' => 'ul',
        'common_support_list_class' => 'common-support-list',
        'common_support_list_itemprop' => '',
      ),
    ),
  );
}


/**
 * Implements hook_field_formatter_Settings_form().
 */
function common_support_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $form = array();

  if ($display['type'] == 'common_support_schema_list') {
    $form['common_support_list_type'] = array(
      '#title' => t("List type"),
      '#type' => 'select',
      '#options' => array(
        'ul' => t("Unordered HTML list (ul)"),
        'ol' => t("Ordered HTML list (ol)"),
        'comma' => t("Comma separated list"),
      ),
      '#default_value' => $settings['common_support_list_type'],
      '#required' => TRUE,
    );
    $form['common_support_list_itemprop'] = array(
      '#title' => t("itemProp"),
      '#type' => 'textfield',
      '#default_value' => $settings['common_support_list_itemprop'],
      '#required' => TRUE,
    );
    $form['common_support_list_class'] = array(
      '#title' => t("List classes"),
      '#type' => 'textfield',
      '#size' => 40,
      '#description' => t("A CSS class to use in the markup for the field list."),
      '#default_value' => $settings['common_support_list_class'],
      '#required' => FALSE,
    );
  }

  $context = array(
    'field' => $field,
    'instance' => $instance,
    'view_mode' => $view_mode
  );
  drupal_alter('common_support_field_formatter_settings_form', $form, $form_state, $context);

  return $form;
}


/**
 * Implements hook_field_formatter_settings_summary().
 */
function common_support_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();

  if ($display['type'] == 'common_support_schema_list') {
    switch ($settings['common_support_list_type']) {
      case 'ul':
        $summary[] = t("Unordered HTML list");
        break;
      case 'ol':
        $summary[] = t("Ordered HTML list");
        break;
    }

    if ($settings['common_support_list_class']) {
      $summary[] = t("CSS Class") . ': <em>' . check_plain($settings['common_support_list_class']) . '</em>';
    }

    if ($settings['common_support_list_itemprop']) {
      $summary[] = t("Schema itemProp") . ': <em>' . check_plain($settings['common_support_list_itemprop']) . '</em>';
    }

    $summary = theme('item_list', array('type' => 'ul', 'items' => $summary));
  }

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function common_support_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  if ($display['type'] == 'common_support_schema_list') {
    $settings = $display['settings'];
    $element = $list_items = array();
    $itemprop = $settings['common_support_list_itemprop'];

    if ($field['type'] == 'text_long') {
      foreach ($items as $delta => $item) {
        // Explode on new line char, trim whitespace (if any), then array filter (So any empty lines will actually be removed).
        $long_text_items = array_filter(array_map('trim', explode("\n", $item['value'])));
        foreach ($long_text_items as $long_text_item) {
          // @see _text_sanitize(), text.module
          $list_item = ($instance['settings']['text_processing'] ? check_markup($long_text_item, $item['format'], $langcode) : field_filter_xss($long_text_item));
          $list_items[] = '<span itemprop="' . $itemprop . '">' . $list_item . '</span>';
        }
      }
    }
    else {
      foreach ($items as $delta => $item) {
        $list_item = ($item['format'] ? check_markup($item['value'], $item['format'], $langcode) : field_filter_xss($item['value']));
        $list_items[] = '<span itemprop="' . $itemprop . '">' . $list_item . '</span>';
      }
    }

    // CSS classes are checked for validity on submission. drupal_attributes()
    // runs each attribute value through check_plain().
    $classes = (!($settings['common_support_list_class'] == '')) ? explode(' ', $settings['common_support_list_class']) : array();
    switch ($settings['common_support_list_type']) {
      case 'ul':
      case 'ol':
        // Render elements as one piece of markup and theme as item list.
        $element[0] = array(
          '#theme' => 'item_list',
          '#type' => $settings['common_support_list_type'],
          '#items' => $list_items,
        );
        if (!empty($classes)) {
          $element[0]['#attributes'] = array(
            'class' => $classes,
          );
        }
        break;
    }
  }
  return $element;
}

/**
 * Checks a view element for a result.
 * Views always returns html whether or not there are results.
 * This sucks because it's hard to use render arrays nicely
 * and check for results, and prevent wrappers etc from rendering
 * in the template. This function unsets an views element if it
 * has no results.
 *
 * @param array $element
 *   The views render array to check.
 */
function common_support_view_check(&$element) {
  if ($view = views_get_view($element['#view'])) {
    $view->set_display($element['#display']);
    $view->preview($element['#display'], (isset($element['#args']) ? $element['#args'] : array()));
    if ($view->result) {
      return;
    }
  }
  $element = NULL;
}

/**
 * Save a nodequeue queue.
 * @see _fe_nodequeue_save_queue() in fe_nodequeue module.
 *
 * @param array $settings
 *   A nodequeue settings array.
 *
 * @return array
 *   The updated settings array.
 */
function common_support_nodequeue_save_queue(array $settings) {
  // Convert roles from names to rids.
  $roles = array_flip(user_roles());
  foreach ((array) $settings['roles'] as $index => $role) {
    // In case we are dealing with an old export with rids, don't do anything.
    if (is_int($role)) {
      continue;
    }
    $settings['roles'][$index] = $roles[$role];
  }

  // Simulate checkboxes.
  $settings['roles'] = drupal_map_assoc($settings['roles']);
  $settings['types'] = drupal_map_assoc($settings['types']);

  // Simulate submitting.
  $form_state = array();
  $form_state['values'] = $settings;
  module_load_include('inc', 'nodequeue', 'includes/nodequeue.admin');
  nodequeue_edit_queue_form_submit(NULL, $form_state);

  // Reset static caches.
  // Note: we are currently using a variant of nodequeue_get_qid_map() that uses
  // drupal_static() instead of a static variable to cache the results.
  // @see http://drupal.org/node/1666556
  drupal_static_reset('_fe_nodequeue_get_qid_map');

  return $settings;
}

/**
 * Return a map of queue name to qid values to aid in various lookups.
 *
 * This is based on nodequeue_get_qid_map() but uses drupal_static() instead of
 * a static variable to cache the results.
 *
 * @see nodequeue_get_qid_map()
 *
 * @todo Add a link to the issue that converts this to drupal_static().
 * @todo Create a followup issue to remove this once the above issue is fixed.
 *   We will need to keep this in for a while to provide backwards compatibility
 *   for people running old versions of Nodequeue.
 *
 * @see _fe_nodequeue_get_qid_map() in fe_nodequeue module.
 *
 * @return array
 *   A array of qids, keyed by machine name.
 */
function common_support_nodequeue_get_qid_map() {
  $map = &drupal_static(__FUNCTION__, array());
  if (!$map) {
    $result = db_query("SELECT qid, name FROM {nodequeue_queue}");
    while ($get = $result->fetchObject()) {
      $map[$get->name] = $get->qid;
    }
  }
  return $map;
}

/**
 * Implements hook_ds_layout_info().
 */
function common_support_ds_layout_info() {
  $path = drupal_get_path('module', 'common_support');

  $layouts = array(
    'common_support_quote_1' => array(
      'label' => t('Quote Layout V1'),
      'path' => $path . '/layouts/common_support_quote_1',
      'regions' => array(
        'quote_body' => t('Quote body'),
        'quote_author' => t('Quote author'),
        'quote_url' => t('Quote url'),
      ),
      'css' => TRUE,
      'image' => TRUE,
    ),
    'common_support_teaser_1' => array(
      'label' => t('Teaser List V1'),
      'path' => $path . '/layouts/common_support_teaser_1',
      'regions' => array(
        'col1' => t('Column 1'),
        'col2' => t('Column 2'),
      ),
      'css' => TRUE,
      'image' => TRUE,
    ),
  );

  return $layouts;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function common_support_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
  if ($module == 'ds' && ($api == 'ds' || $api == 'plugins')) {
    return array('version' => 1);
  }
  if ($module == 'field_group' && $api == 'field_group') {
    return array('version' => 1);
  }
  if (($module == 'file_entity' && $api == 'file_type') || ($module == 'page_manager' && $api == 'pages_default') || $module == 'panelizer') {
    return array('version' => 1);
  }
  if ($module == 'file_entity' && $api == 'file_default_displays') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_views_api().
 */
function common_support_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}
