<?php
/**
 * @file
 * Code for the ID - Twitter feature.
 */

include_once('id_twitter.features.inc');

/**
 *
 * implements hook_theme
 * here we need to register the template for the community feed style.
 * this allows us to add comments into each row result
 *
 * @return $themes
 *   theme array
 */
function id_twitter_theme() {
  $themes['views_view__recent_tweets'] = array(
    'template' => 'views-view--recent-tweets',
    'original hook' => 'views_view',
    'path' => drupal_get_path('module', 'id_twitter') . '/theme',
    'type' => 'module',
    'variables' => array(),
    'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view',
        'id_twitter_preprocess_views_view__recent_tweets'),
  );
  return $themes;
}

/**
 * Preprocess to add variables to the tweets template.
 */
function id_twitter_preprocess_views_view__recent_tweets(&$vars) {
  $vars['more_url'] = check_plain(variable_get('id_twitter_more_url'));
  $vars['more_text'] = check_plain(variable_get('id_twitter_more_text'));
}

/**
 *
 * Implements hook_form_FORM_ID_alter().
 * adds fields to the twitter module config form to allow
 * customizing the url and text for the recent tweets view
 * more link in the footer
 */
function id_twitter_form_twitter_admin_form_alter(&$form, $form_state) {
  $form['id_twitter'] = array(
    '#type' => 'fieldset',
    '#title' => t('Set Recent Tweets More Link URL'),
  );
  $form['id_twitter']['id_twitter_more_url'] =  array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#description' => t('Enter the url to which the Recent Tweets view more link should point'),
    '#default_value' => isset($form_state['values']) ? $form_state['values'] : variable_get('id_twitter_more_url', ''),
  );
  $form['id_twitter']['id_twitter_more_text'] =  array(
    '#type' => 'textfield',
    '#title' => t('Text'),
    '#description' => t('Enter the text for the Recent Tweets view more link'),
    '#default_value' => isset($form_state['values']) ? $form_state['values'] : variable_get('id_twitter_more_text', ''),
  );
}

/**
 * alter node build to rewrite the user name field
 * as a link to their twitter account
 * @param array $node
 */
function id_twitter_node_view_alter(&$build) {
  if ($build['#node']->type == "tweet")  {
    $build['field_tweet_author'][0]['#markup'] = l($build['field_tweet_author'][0]['#markup'], 'http://twitter.com/' . $build['field_tweet_author'][0]['#markup'], array('attributes'=>array('target'=>'_blank')));
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function id_twitter_feeds_plugins() {
  $plugins = array();
  $plugins['FeedsTwitterSearchFetcher'] = array(
    'name' => 'Twitter Search Fetcher',
    'description' => 'Download content from a Twitter search query.',
    'handler' => array(
      'parent' => 'FeedsFetcher', // This is the key name, not the class name.
      'class' => 'FeedsTwitterSearchFetcher',
      'file' => 'FeedsTwitterSearchFetcher.inc',
    ),
  );
  $plugins['FeedsSocialJSONParser'] = array(
    'name' => 'Social Networks JSON Parser',
    'description' => 'Parse JSON payload from social networks, removing wing-dings.',
    'handler' => array(
      'parent' => 'FeedsJSONPathParser', // This is the key name, not the class name.
      'class' => 'FeedsSocialJSONParser',
      'file' => 'FeedsSocialJSONParser.inc',
    ),
  );
  return $plugins;
}
