name = home
description = Layout for the home page
preview = home-layout-preview.png
template = home-layout

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/home/home.layout.css
stylesheets[all][] = css/layouts/home/home.layout.no-query.css

; ========================================
; Scripts
; ========================================
scripts[] = js/jquery.easing.1.3.js
scripts[] = js/waypoints.js
scripts[] = js/parallax-custom.js
scripts[] = js/jquery.stellar.js



; ========================================
; Regions
; ========================================
regions[messages] = Messages
regions[user_bar] = User Bar
regions[mobile_nav] = Mobile Navigation
regions[pre_header] = Pre-Header
regions[header] = Header
regions[branding] = Branding
regions[navigation] = Navigation
regions[pre_content] = Pre-Content
regions[content_1] = Content 1
regions[content_2] = Content 2
regions[content_3] = Content 3
regions[content_4] = Content 4
regions[content_5] = Content 5
regions[content_6] = Content 6
regions[content_7] = Content 7
regions[content_8] = Content 8
regions[content_9] = Content 9
regions[content_10] = Content 10
regions[post_content] = Post-Content
regions[pre_footer] = Pre-Footer
regions[footer] = Footer
regions[footer_1] = Footer Section 1
regions[footer_2] = Footer Section 2