<?php
/**
 * @file
 * sdm.install
 */

/**
 * Implements hook_schema().
 */
function sdm_schema() {
  $schema = array();
  return $schema;
}

/**
 * Implements hook_install().
 */
function sdm_install() {
// ...
}

/**
 * Implements hook_uninstall();
 */
function sdm_uninstall() {
   db_query('DROP TABLE {table_name}');
   db_query('DROP TABLE {table_name}');
   
   cache_clear_all('*', 'cache', TRUE);
}


/**
 * Implements hook_enable().
 */
function sdm_enable() {

}
