<?php
/**
 * @file
 * Code for the Story Blocks feature.
 */

include_once 'story_blocks.features.inc';

/**
 * Implements hook_ds_layout_info().
 */
function story_blocks_ds_layout_info() {
  $path = drupal_get_path('module', 'story_blocks');

  $layouts = array(
    'story_block' => array(
      'label' => t('Story Block Layout'),
      'path' => $path . '/layouts/story_block',
      'regions' => array(
        'col1' => t('Column 1'),
        'col2' => t('Column 2'),
      ),
      'css' => TRUE,
      'image' => TRUE,
    )
  );

  return $layouts;
}
