name = Unconstrained-1
description = Un-constrained layout having 1 column with a sidebar, and the column has 10 content-rows
preview = unconstrained-1-layout.png
template = unconstrained-1-layout

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/unconstrained-1/unconstrained-1-layout.css
stylesheets[all][] = css/layouts/unconstrained-1/unconstrained-1-layout.css

; ========================================
; Scripts
; ========================================


; ========================================
; Regions
; ========================================
regions[mobile_nav] = Mobile Navigation
regions[header] = Header
regions[branding] = Branding
regions[navigation] = Navigation
regions[pre_content] = Pre-Content
regions[content] = Content
regions[content_1] = Content 1
regions[content_2] = Content 2
regions[content_3] = Content 3
regions[content_4] = Content 4
regions[content_5] = Content 5
regions[content_6] = Content 6
regions[content_7] = Content 7
regions[content_8] = Content 8
regions[content_9] = Content 9
regions[content_10] = Content 10
regions[content_11] = Content 11
regions[content_12] = Content 12
regions[content_13] = Content 13
regions[content_14] = Content 14
regions[content_15] = Content 15
regions[pre_footer] = Pre-Footer
regions[footer_1] = Footer Section 1
regions[footer_2] = Footer Section 2
regions[footer_3] = Footer Section 3
